on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  cargo-test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
  get-version:
    needs: cargo-test
    runs-on: macos-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      published: ${{ steps.vars.outputs.published }}
    steps:
      - uses: actions/checkout@v4
      - run: brew install callum-oakley/tap/jfn
      - id: vars
        run: |
          name="$(cat Cargo.toml | jfn -t '$.package.name')"
          version="$(cat Cargo.toml | jfn -t '$.package.version')"
          description="$(cat Cargo.toml | jfn -t '$.package.description')"
          published="$(
            curl -s https://crates.io/api/v1/crates/jog |
              version="${version}" jfn -j '$.versions?.map(a => a.num).includes($version)'
          )"
          echo version="${version}" | tee -a "${GITHUB_OUTPUT}"
          echo published="${published}" | tee -a "${GITHUB_OUTPUT}"
  release-create:
    needs: get-version
    if: ${{ needs.get-version.outputs.published != 'true' }}
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: gh release create v${{ needs.get-version.outputs.version }} --generate-notes
  release-upload:
    needs:
      - get-version
      - release-create
    runs-on: ${{ matrix.runs-on }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - os: macos
            runs-on: macos-latest
            bin: target/release/jog
          - os: linux
            runs-on: ubuntu-latest
            bin: target/release/jog
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - run: |
          archive='jog-${{ needs.get-version.outputs.version }}-${{ matrix.os }}'
          mkdir "${archive}"
          cp ${{ matrix.bin }} "${archive}"
          tar czf "${archive}.tar.gz" "${archive}"
          gh release upload v${{ needs.get-version.outputs.version }} "${archive}.tar.gz"
  homebrew-publish:
    needs:
      - get-version
      - release-upload
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.HOMEBREW_PUBLISH_TOKEN }}
    steps:
      - run: |
          gh api repos/callum-oakley/homebrew-tap/dispatches \
            -f 'event_type=publish' \
            -f 'client_payload[name]=${{ needs.get-version.outputs.name }}' \
            -f 'client_payload[version]=${{ needs.get-version.outputs.version }}' \
            -f 'client_payload[description]=${{ needs.get-version.outputs.description }}'
  cargo-publish:
    needs: get-version
    if: ${{ needs.get-version.outputs.published != 'true' }}
    runs-on: macos-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
